Updating the CI workflow to verify the build after deployment.

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -19,14 +19,28 @@ jobs:
       with:
         go-version: '1.22.1'
 
+    - name: Cache Go Modules
+      uses: actions/cache@v3
+      with:
+        path: |
+          ~/go/pkg/mod
+          ~/.cache/go-build
+        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+        restore-keys: |
+          ${{ runner.os }}-go-
+
+    - name: Download Dependencies
+      run: go mod download
+
     - name: Build
-      run: go build -o slurpy -v ./...
+      run: go build
 
     - name: Run Tests
-      run: go test -v ./...
+      run: go test ./...
+
+    - name: List Files
+      run: ls -la
 
     - name: Verify Build
       run: |
-        if [ ! -f ./slurpy ]; then
-          echo "Build failed or binary not found!"
-          exit 1
+        ./slurpy --help  || (echo "Build failed or binary not found!" && exit 1)
